StudentList/StudentList/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StudentList.Models
{
    [Table("Student")]
    public class Student
    {

        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Фото")]
        public byte[] Photo { get; set; }

        [Required]
        [Display(Name = "Ім'я")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Довжина рядка повинна бути між 3 та 50 символами")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Прізвище")]
        [StringLength(50, ErrorMessage = "Довжина рядка повинна бути між 3 та 50 символами")]
        public string Surname { get; set; }

        [Required]
        [Display(Name = "Факультет")]
        [StringLength(50, ErrorMessage = "Довжина рядка повинна бути між 3 та 50 символами")]
        public string Faculty { get; set; }

        [Required]
        [Display(Name = "Група")]
        [StringLength(50, ErrorMessage = "Довжина рядка повинна бути між 3 та 50 символами")]
        public string Group { get; set; }

        public IEnumerable<Mark> Marks { get; set; }
    }
}

StudentList/StudentList/Controllers/MarkController.cs
using StudentList.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentList.Controllers
{
    public class MarkController : Controller
    {
        //
        // GET: /Mark/

        StudentListContext db = new StudentListContext();

        [HttpGet]
        public ActionResult List(int? id)
        {

            if (id == null)
            {
                return HttpNotFound();
            }

            Student std = db.Students.Find(id);

            if (std == null)
            {
                return HttpNotFound();
            }

            std.Marks = db.Marks.Where(m => m.StudentId == std.Id);

            return View(std);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create(int? studentId)
        {

            if (studentId == null)
            {
                return HttpNotFound();
            }

            Student std = db.Students.Find(studentId);

            if (std == null)
            {
                return HttpNotFound();
            }

            ViewBag.routeId = studentId;

            return View();
        }


        [HttpPost]
        public ActionResult Create(Mark mark, int studentId)
        {
            mark.StudentId = studentId;

            db.Marks.Add(mark);
            db.SaveChanges();
            return RedirectToAction("List", new { id = studentId });
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int? id, int? studentId)
        {
            if (id == null || studentId == null)
                return HttpNotFound();

            Mark mark = db.Marks.Find(id);

            Student std = db.Students.Find(studentId);

            if (std == null || mark == null)
                return HttpNotFound();

            return View(mark);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id, int studentId)
        {
            Mark mark = db.Marks.Find(id);

            mark.StudentId = studentId;

            if (mark == null)
                return HttpNotFound();

            db.Marks.Remove(mark);
            db.SaveChanges();
            return RedirectToAction("List", new { id = studentId });
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int? id, int? studentId)
        {
            if (id == null || studentId == null)
                return HttpNotFound();

            Mark mark = db.Marks.Find(id);

            Student std = db.Students.Find(studentId);

            if (mark == null || std == null)
                return HttpNotFound();

            return View(mark);
        }

        [HttpPost]
        public ActionResult Edit(Mark mark, int studentId)
        {
            mark.StudentId = studentId;

            db.Entry(mark).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("List", new { id = studentId });
        }
    }
}

StudentList/StudentList/Controllers/StudentController.cs
using StudentList.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentList.Controllers
{
    public class StudentController : Controller
    {
        private StudentListContext db = new StudentListContext();

        public ActionResult List()
        {
            return View(db.Students.ToList());
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Student student, HttpPostedFileBase uploadImage)
        {
            if (uploadImage != null)
            {
                byte[] imageData = null;

                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }

                // установка массива байтов
                student.Photo = imageData;

                db.Students.Add(student);
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpNotFound();

            Student student = db.Students.Find(id);

            if (student == null)
                return HttpNotFound();

            return View(student);
        }

        [HttpPost]
        public ActionResult Edit(Student student, HttpPostedFileBase uploadImage)
        {
            if (uploadImage != null)
            {
                byte[] imageData = null;

                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }

                // установка массива байтов
                student.Photo = imageData;

                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
            }
  
            return RedirectToAction("List");
        }

        [Authorize]
        [HttpGet]      
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Student std = db.Students.Find(id);

            if (std == null)
            {
                return HttpNotFound();
            }
            return View(std);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Student std = db.Students.Find(id);

            if (std == null)
            {
                return HttpNotFound();
            }

            db.Students.Remove(std);
            db.SaveChanges();

            return RedirectToAction("List");
        }
    }
}

StudentList/StudentList/Views/Student/Create.cshtml
@model StudentList.Models.Student

@{
    ViewBag.Title = "Create";
}

<h2 style="text-align:center;">Додати нового студента</h2>

@using (Html.BeginForm("Create", "Student", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Surname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Surname)
            @Html.ValidationMessageFor(model => model.Surname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Faculty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Faculty)
            @Html.ValidationMessageFor(model => model.Faculty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Group)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Group)
            @Html.ValidationMessageFor(model => model.Group)
        </div>

        <div class="editor-label">Фото</div>
        <div class="editor-field">
            <input type="file" name="uploadImage" />
        </div>

        <p>
            <button type="submit" class="waves-effect waves-light btn submit">Створити</button>
            <button type="reset" class="waves-effect waves-light btn red " value="Save">@Html.ActionLink("Відмінити", "List",null, new { @class="actionLink"})</button>
        </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentList/StudentList/Views/Student/Delete.cshtml
@model StudentList.Models.Student

@{
    ViewBag.Title = "Delete";
}


<h3 class="center-align">Ви впевнені, що хочете його видалити?</h3>
<div class="center big-text">
    <div class="display-label">
        <b>
            @Html.DisplayNameFor(model => model.Name):
        </b>
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
        <b>
            @Html.DisplayNameFor(model => model.Surname):
        </b>

        @Html.DisplayFor(model => model.Surname)
    </div>

    <div class="display-label">
        <b>
            @Html.DisplayNameFor(model => model.Faculty):
        </b>

        @Html.DisplayFor(model => model.Faculty)
    </div>

    <div class="display-label">
        <b>
            @Html.DisplayNameFor(model => model.Group):
        </b>

        @Html.DisplayFor(model => model.Group)
    </div>
    <div>
        @Html.Raw("<img style='width:250px; height:200px;' src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(Model.Photo) + "\" />")
    </div>
   </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    <div class="buttons">
        <button type="submit" class="waves-effect waves-light btn red">Видалити</button>
        <button type="reset" class="waves-effect waves-light btn " value="Save">@Html.ActionLink("Відмінити", "List",null, new { @class="actionLink"})</button>
    </div>
    }

StudentList/StudentList/Views/Student/Edit.cshtml
@model StudentList.Models.Student

@{
    ViewBag.Title = "Edit";
}

<h2 class="center-align">Редагування</h2>

@using (Html.BeginForm("Edit", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Surname)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Surname)
            @Html.ValidationMessageFor(model => model.Surname)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Faculty)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Faculty)
            @Html.ValidationMessageFor(model => model.Faculty)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Group)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Group)
            @Html.ValidationMessageFor(model => model.Group)
        </div>

        <div class="editor-label">Фото</div>
        <div class="editor-field">
            <input type="file" name="uploadImage" />
        </div>

        <p>
            <button type="submit" class="waves-effect waves-light btn submit">Зберегти</button>
            <button type="reset" class="waves-effect waves-light btn red">@Html.ActionLink("Відмінити", "List",null,new {  @class ="actionLink"})</button>
        </p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentList/StudentList/Views/Student/List.cshtml
@model IList<StudentList.Models.Student>

@{
    ViewBag.Title = "List";
}

<h2 class="center-align">Cписок студентів</h2>
<div class="center-align">
<table class="stripped main">
    <tr>
        <th>
            Ім'я
        </th>
        <th>
            Прізвище
        </th>
        <th>
            Факультет
        </th>
        <th>
            Група
        </th>
        <th>
            Фотокартка
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Faculty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td>
                @Html.Raw("<img style='width:70px; height:70px;' src=\"data:image/jpeg;base64,"
                                + Convert.ToBase64String(item.Photo) + "\" />")
            <td>
                <div class="waves-effect waves-light btn function-button">@Html.ActionLink("Редагувати", "Edit", new { id = item.Id }, new { @class = "actionLink" }) </div>
                <div class="waves-effect waves-light btn function-button">@Html.ActionLink("Детальніше", "List", "Mark", new { id = item.Id }, new { @class="actionLink"}) </div>
                <div class="waves-effect waves-light btn function-button red">@Html.ActionLink("Видалити", "Delete", new { id = item.Id }, new { @class = "actionLink" })</div>
            </td>
        </tr>
    }
</table>
    <br/>
    <div><a class="waves-effect waves-light btn" href="@Url.RouteUrl("createStudent")">Cтворити нового студента</a></div>
</div>